// All visible texts of Touch Shading, as one object over src/i18n (keys `shading.*` in
// src/i18n/{en,de}/shading.ts). Call sites use T.menu, T.restored(n) …; the language is the
// UI language (Settings → Interface).
import { t, type Key } from '../i18n';

export const T = {
  get menu() { return t('shading.menu'); },
  get buttonTitle() { return t('shading.buttonTitle'); },
  get simName() { return t('shading.simName'); },
  get simCard() { return t('shading.simCard'); },
  get chooseTargetFirst() { return t('shading.chooseTargetFirst'); },
  get simNote() { return t('shading.simNote'); },
  restored: (n: number) => t('shading.restored', { n }),
  get notConnected() { return t('shading.notConnected'); },
  get vectorCentre() { return t('shading.vectorCentre'); },
  notControllable: (labels: string, mode: string) => t('shading.notControllable', { labels, mode }),
  unknownValue: (labels: string) => t('shading.unknownValue', { labels }),
  get hueSimOnly() { return t('shading.hueSimOnly'); },
  tripleUnknown: (k: string) => t('shading.tripleUnknown', { k }),
  get hueNotOnBus() { return t('shading.hueNotOnBus'); },
  get badgeSim() { return t('shading.badgeSim'); },
  badgeCam: (n: number) => t('shading.badgeCam', { n }),
  target: (lvl: string, grab: string) => t('shading.target', { lvl, grab }),
  get vectorHint() { return t('shading.vectorHint'); },
  get targetTitle() { return t('shading.targetTitle'); },
  get chooseTarget() { return t('shading.chooseTarget'); },
  get simOption() { return t('shading.simOption'); },
  camOption: (n: number, label: string, connected: boolean, mode: string) =>
    `${t('shading.camOption', { n, label })}${connected ? '' : t('shading.disconnected')}${mode ? ` · ${mode}` : ''}`,
  get urlTitle() { return t('shading.urlTitle'); },
  linkOpen: (n: number) => t('shading.linkOpen', { n }),
  get linkConnecting() { return t('shading.linkConnecting'); },
  get linkClosed() { return t('shading.linkClosed'); },
  get active() { return t('shading.active'); },
  get undoTitle() { return t('shading.undoTitle'); },
  get undo() { return t('shading.undo'); },
  get stopTitle() { return t('shading.stopTitle'); },
  get stop() { return t('shading.stop'); },
  help: (step: number, span: number) => t('shading.help', { step, span }),
  get close() { return t('shading.close'); },
  get moveBar() { return t('shading.moveBar'); },
  camN: (n: number) => t('shading.camN', { n }),
  get unreachable() { return t('shading.unreachable'); },
  get error() { return t('shading.error'); },
  get setupTitle() { return t('shading.setup.title'); },
  get setupStep1() { return t('shading.setup.step1'); },
  get setupDownload() { return t('shading.setup.download'); },
  get setupStep2() { return t('shading.setup.step2'); },
  get setupStep3() { return t('shading.setup.step3'); },
  get setupStep4() { return t('shading.setup.step4'); },
  get setupSim() { return t('shading.setup.sim'); },
  get setupNoCameras() { return t('shading.setup.noCameras'); },
  get setupStep1Desktop() { return t('shading.setup.step1Desktop'); },
  get setupStep2App() { return t('shading.setup.step2App'); },
  get camMenu() { return t('shading.cam.menu'); },
  get camMenuTitle() { return t('shading.cam.menuTitle'); },
  bridgeState: (state: string, p: { port: number; version: string; message: string }) => t(`shading.setup.bridge.${state}` as Key, p),
};
